export const ActionTypes = {
    GET_NUMBER_CART: 'GET_NUMBER_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    CLEAR_CART:'CLEAR_CART',
    REMOVE_ITEM:'REMOVE_ITEM',
    INCREASE_QUANTITY:'INCREASE_QUANTITY',
    DECREASE_QUANTITY:'DECREASE_QUANTITY',
    ADD_TO_FAVORITES:'ADD_TO_FAVORITES',
    REMOVE_TO_FAVORITE:'REMOVE_TO_FAVORITES'
    
}